name: github-actions-lint

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        - name: Run install
          run: make install
        - name: Run linter
          run: make linter